### ISSUE TITLE
Board with size 0x0 crashes game

### ISSUE THREAD

**Issue by svisser** [jordimarinvalle/tictactoexxl#1]
If I run `tictactoexxl-play.py -x 0 -y 0` the game terminates without really explaining what's wrong:

```
tictactoexxl.game.GameSetupWinningError: Game error, setup params will not create a fair game.
```

**Comment by jordimarinvalle** [comment]
Totally agree. An exception was not captured and also did not provide a useful explanation related with board dimensions. I'm on my way to fixing this.
